### ISSUE TITLE
[PE-D] Error message for name in add patient command

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T09-3/tp#138]
![image.png](https://raw.githubusercontent.com/froststein/ped/main/files/b37071f6-073c-4c6e-a6ee-29b5a4461295.png)

For the name segment of the command, the error message is the same when I entered a number in the name and when I entered a special character. Consider splitting the type of error messages.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: froststein/ped#1

**Comment by wraineflores** [comment]
We don't allow special characters. That includes numbers

**Comment by tanweili** [comment]
Perhaps the error message can include numbers if possible
