### ISSUE TITLE
[PE-D] Gender character specification

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T09-3/tp#142]
![image.png](https://raw.githubusercontent.com/froststein/ped/main/files/93049183-1fda-4b2d-96be-32cfdf216af3.png)

Usability affected where m and f is not recognized, consider accepting values such as M, m, F, f for usability. 

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: froststein/ped#4

**Comment by tanweili** [comment]
Fixed in PR #189
