### ISSUE TITLE
[PE-D] View patient alternative format does not work as expected

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T09-3/tp#143]
![image.png](https://raw.githubusercontent.com/bbawj/ped/main/files/b8befec3-6778-434e-831b-ffda604a747c.png)

Unable to view patient when using the format view patient /info [nric]

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: bbawj/ped#2

**Comment by tanweili** [comment]
@wraineflores I believe you did the Finder class / commands for the lists? Can I get you to help with this?

**Comment by wraineflores** [comment]
@tanweili I think we just remove this view parameter feature from the UG (Doctor, Patient & Medicine classes) permanently so that users will not get the wrong ideas. We'll only have the find parameter feature as a focus. View Doctor, View Patient & View Medicine is to list all instead
