### ISSUE TITLE
[PE-D] View patient command not working with NRIC argument

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T09-3/tp#144]
![image.png](https://raw.githubusercontent.com/froststein/ped/main/files/6c218784-615e-47ed-a1d1-b9ba60bad4dd.png)

The view patient command does not work when NRIC is supplied as an argument.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: froststein/ped#5

**Comment by tanweili** [comment]
Error due to UG DG not being update in time. Fixing in PR #178
