### ISSUE TITLE
[PE-D] Edit table displayed wrongly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T09-3/tp#145]
![Screenshot (837).png](https://raw.githubusercontent.com/Yzkkk/ped/main/files/74f30e83-3e3e-45ba-a7be-cd2cadc8085d.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Yzkkk/ped#1

**Comment by tanweili** [comment]
Fixed by PR #189
