### ISSUE TITLE
[PE-D] View command for patient user guide example

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T09-3/tp#147]
![image.png](https://raw.githubusercontent.com/froststein/ped/main/files/bb099ecb-693c-4a50-8fce-3813adae8b60.png)

Wrong command example for view patient.
Should be `view patient /info S1234567A`

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: froststein/ped#6

**Comment by tanweili** [comment]
Fixing in PR #178
