### ISSUE TITLE
[PE-D] Typo in UI for edit doctor

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T09-3/tp#154]
![image.png](https://raw.githubusercontent.com/bbawj/ped/main/files/5be8e538-fc64-40ec-b873-6bcda33d675a.png)

There is a typo in the UI. When editing doctors, the UI references patients instead.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: bbawj/ped#6

**Comment by kktai1512** [comment]
#190
