### ISSUE TITLE
[PE-D] Edit doctor results in unexpected changes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T09-3/tp#158]
The editing of doctors result in an unexpected change in the data fields. Changing the address results in Address becoming Gender and Gender is replaced with a number.

![image.png](https://raw.githubusercontent.com/bbawj/ped/main/files/248a9f3a-df55-423b-92f9-825f2710454c.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: bbawj/ped#7

**Comment by kktai1512** [comment]
#190
