### ISSUE TITLE
[PE-D] View appointment examples in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T09-3/tp#160]
![image.png](https://raw.githubusercontent.com/froststein/ped/main/files/d3e0516e-8e56-4793-882d-8a612037c6cf.png)

Perhaps you could split up the examples into bullet points for ease of reading.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: froststein/ped#13

**Comment by Anvitha-r** [comment]
implemented the changes
