### ISSUE TITLE
[PE-D] Failed to find doctor by gender

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T09-3/tp#161]
![Screenshot (843).png](https://raw.githubusercontent.com/Yzkkk/ped/main/files/9c1f651c-456f-41fb-aa13-18f04cb0e829.png)

The find command is also affected by the edit command.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Yzkkk/ped#4

**Comment by kktai1512** [comment]
#190
