### ISSUE TITLE
[DG review] T09-3

### ISSUE THREAD

**Issue by slewyh** [AY2122S2-CS2113T-T09-3/tp#170]
1. How about making the colour scheme and font size consistent across diagrams?
> The architecture diagram and sequence diagram below do not look similar in style.  
<img width="400" alt="Screenshot 2022-04-04 at 1 03 01 PM" src="https://user-images.githubusercontent.com/43779956/161477280-c6061e4a-38f8-437e-afde-356a105d60ca.png"><img width="574" alt="Screenshot 2022-04-04 at 1 03 09 PM" src="https://user-images.githubusercontent.com/43779956/161477297-3e29f4ea-7f1f-42af-b029-24471d15118e.png">

2. Class diagram notation
> a. Remove non-standard syntax - icons next to class name.
> b. Replace accessor icons as `+`, `-`, or `#`.
<img width="657" alt="Screenshot 2022-04-04 at 1 06 51 PM" src="https://user-images.githubusercontent.com/43779956/161477604-970066f6-be66-43ea-a6c6-ea7ccaea21f6.png">

3. Class diagram usage
> How about drawing meaningful associations between the following classes? 
<img width="448" alt="Screenshot 2022-04-04 at 1 10 43 PM" src="https://user-images.githubusercontent.com/43779956/161478029-e263ad0f-2f98-44a3-9aac-04c2751a683f.png"><img width="293" alt="Screenshot 2022-04-04 at 1 10 37 PM" src="https://user-images.githubusercontent.com/43779956/161478027-07c89083-3ef2-4890-ab8a-d7a077d9ac3f.png"><img width="316" alt="Screenshot 2022-04-04 at 1 10 19 PM" src="https://user-images.githubusercontent.com/43779956/161478024-2c0cc85b-ed7a-40d0-a025-4745543b9a2e.png"><img width="437" alt="Screenshot 2022-04-04 at 1 10 14 PM" src="https://user-images.githubusercontent.com/43779956/161478010-5e609213-7a4c-43e5-b774-d4a62399b018.png">

4.  Sequence diagram notation
To edit:
> Return arrows as dashed lines.
> Omit entity boxes below lifeline
> Redraw [self-invocation](https://nus-cs2113-ay2122s2.github.io/website/se-book-adapted/chapters/uml.html#self-invocation)
<img width="463" alt="Screenshot 2022-04-04 at 1 15 15 PM" src="https://user-images.githubusercontent.com/43779956/161479205-0408f14f-e239-4c3c-8c0e-02a4dcfe67f7.png">

>  Parameter for method call should be enclosed with `()` not `[]`.
> Redraw [constructor call](https://nus-cs2113-ay2122s2.github.io/website/se-book-adapted/chapters/uml.html#object-creation) arrow.
<img width="426" alt="Screenshot 2022-04-04 at 1 19 01 PM" src="https://user-images.githubusercontent.com/43779956/161479187-319e0fd2-1378-480f-bdcd-1df0bd1f0667.png">

5. To fill in missing sections
> Include version number
<img width="189" alt="Screenshot 2022-04-04 at 1 27 05 PM" src="https://user-images.githubusercontent.com/43779956/161480192-c5f6bc60-dca5-4c03-8e41-c20a6cbaeb80.png">

> **Design considerations** in Implementation section

6. Reformatting required
> Replace the markup below:
<img width="366" alt="Screenshot 2022-04-04 at 1 26 35 PM" src="https://user-images.githubusercontent.com/43779956/161480272-104f385f-2f72-469e-a02a-f03fcedfbfd9.png">

7.  Manual testing section
<img width="400" alt="Screenshot 2022-04-04 at 1 32 16 PM" src="https://user-images.githubusercontent.com/43779956/161479978-4ddb5906-7f74-41f3-abeb-f7306b6eb1f6.png">
>  The manual testing section could include both valid and invalid parameters as test cases, showing the expected outputs. The UG on the other hand, tends to omit the special cases.  Refer to an [AB3 example](https://se-education.org/addressbook-level3/DeveloperGuide.html#deleting-a-person) here.

**Comment by shxr3f** [comment]
Changes contribute be everyone in respective PRs
